name: 'Prepare .deb release'
description: 'Prepare debian/changelog file for a new release'
author: 'Andreea Lutac'

inputs:
  package:
    description: 'Package name'
    required: true
  project-dir:
    description: 'Path containing debian folder'
    required: false
    default: '.'
  version:
    description: 'Version to package'
    required: true
  changelog:
    description: 'Changelog to include'
    required: false
    default: 'New release'
  distribution:
    description: 'Codename of distribution (e.g. focal, jammy)'
    required: false
    default: 'unstable'
  user:
    description: 'Full name of release signer'
    required: true
  email:
    description: 'Email of release signer'
    required: true
  use-sudo:
    description: 'Use sudo to install devscripts'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Install devscripts
      shell: bash
      env:
        SUDO: "${{ fromJSON('{ \"true\": \"sudo\", \"false\": \"\" }')[inputs.use-sudo] }}"
      run: |
        ${SUDO} apt-get update
        ${SUDO} apt-get install -y devscripts

    - name: Check if version string contains 'v' and strip it out
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        echo "VERSION=${VERSION#*v}" >> $GITHUB_ENV

    - name: Create or update changelog
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      env:
        DEBFULLNAME: ${{ inputs.user }} 
        DEBEMAIL: ${{ inputs.email }}
      run: |
        if [ ! -f debian/changelog ]; then
          CREATE="--create"
        fi
        dch ${CREATE} --package ${{ inputs.package }} --distribution ${{ inputs.distribution }} --newversion ${{ env.VERSION }} "${{ inputs.changelog }}"
