name: 'Prepare .deb release'
description: 'Prepare debian/changelog file for a new release'
author: 'Andreea Lutac'

inputs:
  package:
    description: 'Package name'
    required: true
  project-dir:
    description: 'Path containing debian folder'
    required: false
    default: '.'
  version:
    description: 'Version to package'
    required: true
  changelog:
    description: 'Changelog to include'
    required: false
    default: 'New release'
  distribution:
    description: 'Codename of distribution (e.g. focal, jammy)'
    required: false
    default: 'unstable'
  user:
    description: 'Full name of release signer'
    required: true
  email:
    description: 'Email of release signer'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install devscripts
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: devscripts

    - name: Check if version string contains 'v' and strip it out
      shell: bash
      run: |
        RAW_VERSION=${{ inputs.version }};
        if [ "${RAW_VERSION#*v}" != "$RAW_VERSION" ]; then
          echo "VERSION=${RAW_VERSION#*v}" >> $GITHUB_ENV;
        fi

    - name: Create or update changelog
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      env:
        DEBFULLNAME: ${{ inputs.user }} 
        DEBEMAIL: ${{ inputs.email }}
      run: |
        if [ ! -f debian/changelog ]; then
          CREATE="--create"
        fi
        dch $CREATE --package ${{ inputs.package }} --distribution ${{ inputs.distribution }} --newversion ${{ env.VERSION }} "${{ inputs.changelog }}"
 